const bcrypt = require('bcryptjs')
const data = {
  users: [
    {
      name: 'Whimzy',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Whimzy',
        logo: '/images/logo1.png',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
     
      name: 'Cap',
      category: 'Cap',
      image: '/images/img1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Cap',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
    {
      
      name: 'Shoes',
      category: 'Shoes',
      image: '/images/img2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Shoes',
      rating: 4.0,
      numReviews: 1,
      description: 'high quality product',
    },
    {
     
      name: 'Cap',
      category: 'Cap',
      image: '/images/img3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Cap',
      rating: 4.8,
      numReviews: 1,
      description: 'high quality product',
    },
    {
     
      name: 'Cap',
      category: 'Cap',
      image: '/images/img4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Cap',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
    {
     
      name: 'Cap',
      category: 'Cap',
      image: '/images/img5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Cap',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
    {
      
      name: 'Necklece',
      category: 'Necklece',
      image: '/images/img6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Necklece',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
    {
      
      name: 'Cap',
      category: 'Cap',
      image: '/images/img7.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Cap',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
    {
     
      name: 'Knife',
      category: 'Knife',
      image: '/images/img8.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Knife',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
    {
     
      name: 'Necklece',
      category: 'Necklece',
      image: '/images/img9.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Necklece',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
    {
     
      name: 'Cap',
      category: 'Cap',
      image: '/images/img10.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Cap',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
   
    {
    
      name: 'Necklece',
      category: 'Necklece',
      image: '/images/img12.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Necklece',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
    {
    
      name: 'Shoes',
      category: 'Shoes',
      image: '/images/img13.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Shoes',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
    {
      
      name: 'Mat',
      category: 'Mat',
      image: '/images/img14.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Mat',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
    {
     
      name: 'Shoes',
      category: 'Shoes',
      image: '/images/img15.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Shoes',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
    {
      
      name: 'Necklece',
      category: 'Necklece',
      image: '/images/img16.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Necklece',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
    {
     
      name: 'Shoes',
      category: 'Shoes',
      image: '/images/img17.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Shoes',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
    {
    
      name: 'Bag',
      category: 'Bag',
      image: '/images/img18.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Bag',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
    {
     
      name: 'Idol',
      category: 'Idol',
      image: '/images/img20.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Idol',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
    {
      
      name: 'Bag',
      category: 'Bag',
      image: '/images/img21.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Bag',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
    {
     
      name: 'Shoes',
      category: 'Shoes',
      image: '/images/img22.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Shoes',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
    {
    
      name: 'Necklece',
      category: 'Necklece',
      image: '/images/img24.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Necklece',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
    {
    
      name: 'Jacket',
      category: 'Jacket',
      image: '/images/img25.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Jacket',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
    {
    
      name: 'Shoes',
      category: 'Shoes',
      image: '/images/img26.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Shoes',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
    {
     
      name: 'Bowl',
      category: 'Bowl',
      image: '/images/img27.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Bowl',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
    {
    
      name: 'Knife',
      category: 'Knife',
      image: '/images/img28.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Knife',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
    {
     
      name: 'Knife',
      category: 'Knife',
      image: '/images/img29.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Knife',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
    {
     
      name: 'Bag',
      category: 'Bag',
      image: '/images/img30.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Bag',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
    {
     
      name: 'Mat',
      category: 'Mat',
      image: '/images/img31.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Mat',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
    {
     
      name: 'Ring',
      category: 'Ring',
      image: '/images/img32.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Ring',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
    {
     
      name: 'Idol',
      category: 'Idol',
      image: '/images/img33.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Idol',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
   
  ],
};
// export default data;
module.exports = data;
